all:
	gcc -Iinclude/ src/app.c src/camera.c src/main.c src/scene.c src/texture.c src/utils.c src/model.c src/load.c src/info.c src/draw.c -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32 -lm -o stage.exe -Wall -Wextra -Wpedantic
